/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-peak_selection
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_PEAK_SELECTION_API_H
#define INCLUDED_PEAK_SELECTION_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_peak_selection_EXPORTS
#define PEAK_SELECTION_API __GR_ATTR_EXPORT
#else
#define PEAK_SELECTION_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_PEAK_SELECTION_API_H */
