/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(peak_selection.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(e9cd90286d0d01c1ff713ec49cc4733f)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <peak_selection/peak_selection.h>
// pydoc.h is automatically generated in the build directory
#include <peak_selection_pydoc.h>

void bind_peak_selection(py::module& m)
{

    using peak_selection    = ::gr::peak_selection::peak_selection;


    py::class_<peak_selection, gr::block, gr::basic_block,
        std::shared_ptr<peak_selection>>(m, "peak_selection", D(peak_selection))

        .def(py::init(&peak_selection::make),
           py::arg("vec_len_"),
           D(peak_selection,make)
        )
        



        ;




}








